# Generated by Django 4.0.4 on 2022-06-02 17:27

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='arrival/%Y/%m/%d', verbose_name='New arrival product image')),
                ('name', models.TextField(max_length=200, verbose_name='New arrival')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Category Url')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Product image')),
                ('name', models.CharField(max_length=50, verbose_name='Product name')),
                ('after_price_text', models.TextField(max_length=200, verbose_name='Product text ')),
                ('description_text', models.TextField(max_length=500, verbose_name='Product description')),
                ('additional_text', models.TextField(max_length=1000, verbose_name='Product additional info')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale product price')),
                ('is_active', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=15, verbose_name='Product visibility')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Product')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Sale product')),
                ('is_new', models.BooleanField(default=True, verbose_name='Product is new')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Product url')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='SlickImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Additional product image')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Review author name')),
                ('message', models.TextField(max_length=500, verbose_name='Review message')),
                ('email', models.EmailField(max_length=100, verbose_name='Author Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('is_active', models.BooleanField(default=True, verbose_name='Reviews visibility')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ColorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Product size')),
                ('color', models.CharField(max_length=15, verbose_name='Product color')),
                ('stock', models.PositiveIntegerField(verbose_name='Product quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Product')),
            ],
        ),
    ]
